apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: my-app:0.1.0  # Replace with your Docker image name
          ports:
            - containerPort: 8080  # The port on which the Spring Boot app listens
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"  # Set active Spring profile if needed
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8080  # External port
      targetPort: 8080  # Internal container port
  type: LoadBalancer  # Expose the service as a load balancer (for cloud environments)
